location __PATH__/ {
    proxy_pass http://127.0.0.1:__PORT_HTTP__/;

    include proxy_params_no_auth;
    proxy_set_header Authorization $http_authorization;

    proxy_buffering off;
    proxy_cache off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
}
