#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Updating the Gitea MCP reverse proxy..." --weight=1
ynh_config_change_url_nginx

ynh_script_progression --message="Change of URL completed for $app" --last
