#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Restoring Gitea MCP files..." --weight=2
ynh_restore_file --origin_path="$install_dir"
ynh_restore_file --origin_path="$data_dir"
ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

chown -R "$app:$app" "$install_dir" "$data_dir"
usermod -aG docker "$app"
systemctl daemon-reload
ynh_systemd_action --service_name="docker" --action="start" --log_path="systemd"

yunohost service add "$app" --description="Official Model Context Protocol server for Gitea" --log="systemd"

ynh_script_progression --message="Starting restored Gitea MCP..." --weight=1
ynh_systemd_action --service_name="$app" --action="start" --log_path="systemd"
ynh_systemd_action --service_name="$app" --action="status" --log_path="systemd"

ynh_script_progression --message="Restore of $app completed" --last
